### ISSUE TITLE
JS corrections don't disappear from vervoeging test after another question

### ISSUE THREAD

**Issue by cmw0513** [lienvdsteen/werkwoorden#13]
If the user gets a question wrong, and the following question right, the corrections from the first question are still there when beginning the third question.

**Comment by lienvdsteen** [comment]
oops :see_no_evil:

**Comment by lienvdsteen** [comment]
I think what we need to do is, in this js add the line `$('.error-message').html('');` 

```
function fade_out() {
  $('.icon-check').fadeOut().empty();
}
```

@cmw0513 does it also not work for the translations?

**Comment by lienvdsteen** [comment]
merged
